//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioAdmon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ColegioEntities : DbContext
    {
        public Db_ColegioEntities()
            : base("name=Db_ColegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Autenticacion> Tbl_Autenticacion { get; set; }
        public virtual DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
    }
}
