//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioAdmon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Autenticacion
    {
        public int Id_Autenticacion { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Rol { get; set; }
    
        public virtual Tbl_Rol Tbl_Rol { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
